Move proxied tool registration to app lifecycle (#513)
## Summary
Closes #498 - the issue has the full details for what changed and why!

## Checklist
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation (in
https://github.com/dbt-labs/docs.getdbt.com) if required -- Mention it
here
- [ ] I have added tests that prove my fix is effective or that my
feature works
- [x] New and existing unit tests pass locally with my changes

## Additional Notes
<!-- Any additional information that would be helpful for reviewers -->

Verification:

Running `uvx dbt-mcp==1.7.0` will raise the error; however, if on this
branch and building locally with `uv sync`, the `RuntimeError` no longer
gets thrown.

<details>
<summary>dbt-mcp==1.7.0 throws error in logs</summary>

```bash
(dbt-mcp) jairus.martinez@BDMACMB-WPC7452QQK dbt-mcp % uvx dbt-mcp==1.7.0
INFO [dbt_mcp.mcp.server] Registering semantic layer tools
INFO [dbt_mcp.mcp.server] Registering discovery tools
INFO [dbt_mcp.mcp.server] Registering dbt cli tools
INFO [dbt_mcp.mcp.server] Registering dbt codegen tools
INFO [dbt_mcp.mcp.server] Registering dbt admin API tools
INFO [dbt_mcp.mcp.server] Registering proxied tools
INFO [dbt_mcp.config.settings] Settings: { ... }
INFO [httpx] HTTP Request: POST https://cloud.getdbt.com/api/ai/v1/mcp/ "HTTP/1.1 200 OK"
INFO [mcp.client.streamable_http] Negotiated protocol version: 2025-11-25
INFO [httpx] HTTP Request: POST https://cloud.getdbt.com/api/ai/v1/mcp/ "HTTP/1.1 202 Accepted"
INFO [httpx] HTTP Request: POST https://cloud.getdbt.com/api/ai/v1/mcp/ "HTTP/1.1 200 OK"
INFO [dbt_mcp.proxy.tools] Loaded proxied tools: get_related_models, text_to_sql, execute_sql
INFO [dbt_mcp.mcp.server] Registering LSP tools
ERROR [asyncio] an error occurred during closing of asynchronous generator <async_generator object streamablehttp_client at 0x10ac00600>
asyncgen: <async_generator object streamablehttp_client at 0x10ac00600>
  + Exception Group Traceback (most recent call last):
  |   File "/Users/jairus.martinez/.cache/uv/archive-v0/0rJWsStAxqIGbZi6yhixV/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 783, in __aexit__
  |     raise BaseExceptionGroup(
  | BaseExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/jairus.martinez/.cache/uv/archive-v0/0rJWsStAxqIGbZi6yhixV/lib/python3.12/site-packages/mcp/client/streamable_http.py", line 620, in streamablehttp_client
    |     yield (
    | GeneratorExit
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jairus.martinez/.cache/uv/archive-v0/0rJWsStAxqIGbZi6yhixV/lib/python3.12/site-packages/mcp/client/streamable_http.py", line 596, in streamablehttp_client
    async with anyio.create_task_group() as tg:
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairus.martinez/.cache/uv/archive-v0/0rJWsStAxqIGbZi6yhixV/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 789, in __aexit__
    if self.cancel_scope.__exit__(type(exc), exc, exc.__traceback__):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairus.martinez/.cache/uv/archive-v0/0rJWsStAxqIGbZi6yhixV/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 461, in __exit__
    raise RuntimeError(
RuntimeError: Attempted to exit cancel scope in a different task than it was entered in
INFO [dbt_mcp.mcp.server] Starting MCP server
INFO [dbt_mcp.lsp.providers.local_lsp_connection_provider] Using LSP binary in /Users/jairus.martinez/Library/Application Support/code/User/globalStorage/dbtlabsinc.dbt/bin/dbt-lsp with version 2.0.0-preview.92
INFO [dbt_mcp.lsp.lsp_connection] LSP server started with PID: 17336
INFO [dbt_mcp.lsp.providers.local_lsp_connection_provider] LSP connection started successfully
INFO [dbt_mcp.lsp.lsp_connection] LSP server initialized successfully
INFO [dbt_mcp.lsp.providers.local_lsp_connection_provider] LSP connection initialized successfully
```
</details>


<details>
<summary>dbt-mcp using local branch no longer throws error</summary>

```bash
(dbt-mcp) jairus.martinez@BDMACMB-WPC7452QQK dbt-mcp % uv sync              
Resolved 87 packages in 0.98ms
Audited 85 packages in 0.11ms
(dbt-mcp) jairus.martinez@BDMACMB-WPC7452QQK dbt-mcp % dbt-mcp           
INFO [dbt_mcp.mcp.server] Registering semantic layer tools
INFO [dbt_mcp.mcp.server] Registering discovery tools
INFO [dbt_mcp.mcp.server] Registering dbt cli tools
INFO [dbt_mcp.mcp.server] Registering dbt codegen tools
INFO [dbt_mcp.mcp.server] Registering dbt admin API tools
INFO [dbt_mcp.mcp.server] Registering LSP tools
INFO [dbt_mcp.mcp.server] Starting MCP server
INFO [dbt_mcp.mcp.server] Registering proxied tools
INFO [dbt_mcp.config.settings] Settings: { ... }
INFO [httpx] HTTP Request: POST https://cloud.getdbt.com/api/ai/v1/mcp/ "HTTP/1.1 200 OK"
INFO [mcp.client.streamable_http] Negotiated protocol version: 2025-11-25
INFO [httpx] HTTP Request: POST https://cloud.getdbt.com/api/ai/v1/mcp/ "HTTP/1.1 202 Accepted"
INFO [httpx] HTTP Request: POST https://cloud.getdbt.com/api/ai/v1/mcp/ "HTTP/1.1 200 OK"
INFO [dbt_mcp.proxy.tools] Loaded proxied tools: get_related_models, text_to_sql, execute_sql
INFO [dbt_mcp.lsp.providers.local_lsp_connection_provider] Using LSP binary in /Users/jairus.martinez/Library/Application Support/code/User/globalStorage/dbtlabsinc.dbt/bin/dbt-lsp with version 2.0.0-preview.92
INFO [dbt_mcp.lsp.lsp_connection] LSP server started with PID: 21151
INFO [dbt_mcp.lsp.providers.local_lsp_connection_provider] LSP connection started successfully
INFO [dbt_mcp.lsp.lsp_connection] LSP server initialized successfully
INFO [dbt_mcp.lsp.providers.local_lsp_connection_provider] LSP connection initialized successfully
```
</details>

---------

Co-authored-by: Devon Fulcher <24593113+DevonFulcher@users.noreply.github.com>